---
title: "Summary of US Catch of Pacific Blue Marlin"
format: html
---

## Introduction 

U.S. fisheries for blue marlin (*Makaira mazara*) in the Pacific Ocean can be categorized according to three distinct gear types: longline, troll, and handline.  The Hawaii longline fishery is the largest and includes Hawaii and California-based vessels (@tbl-annualcatch).  This fishery catches blue marlin incidentally on sets targeting tuna or swordfish. The American Samoa longline fishery also catches blue marlin incidentally and is primarily in the South Pacific Ocean. Troll fisheries in Hawaii, Guam, and the Commonwealth of the Northern Mariana Islands (CNMI) take the second largest catches of marlins. These fisheries opportunistically target marlins on a seasonal basis.  The Hawaii handline fishery represents the third category, with small incidental catches of marlin.  Blue marlin are also caught by recreational fisheries but there is no mandatory data collection program for this fishery sector, therefore, only the U.S. commercial fisheries are discussed in this report.
 
### U.S. Longline Fisheries

The longline gear consists of a single monofilament mainline about 30 to 80 km in length with floats attached to the mainline to support the gear in the water column.  Branchlines with baited hooks are attached to the mainline between the floats.  Gear configurations and operational techniques differ according to target species (i.e., tunas, Thunnus spp., and swordfish, Xiphias gladius) (Ito and Machado, 2001).  Deep-set longline fishing targets tunas. Gear is usually set in the morning and then hauled back around sunset; Pacific sauries *Cololabis saira* or sardines (*Clupeidae*) are used for bait; 15 or more hooks are set between floats; and a line thrower is used (Kawamoto *et al.,* 1989).  The latter creates slack in the mainline, which causes the gear to sag between floats as it sinks and results in a “deep-set”.  In contrast, shallow-set longline fishing is used to target swordfish and  gear is typically set after dusk and with haulback beginning around dawn the following morning, uses mackerel *Scomber japonicus* or mackerel-like bait, attaches chemical lightsticks to the branchlines, and typically sets 4-5 hooks between floats (Ito *et al.,* 1994; PIRO, 2014).  Since the gear and technique for swordfish is fishing relatively shallow, a line thrower is not needed and is referred to as “shallow-set” longline fishing. The deep-set longline sector accounts for majority of the effort and blue marlin landings for this fishery.

The Hawaii-based vessels in the U.S. longline fishery have operated under a limited-access program since 1994.  This program capped participation at 164 vessels, although the number of active vessels has never reached this limit.  Participation by the U.S. Hawaii longline fishery was 150 active vessels in 2024 (deep- and shallow-set sectors combined). Two other important characteristics of this fishery are its geographic range and the annual number of hooks set.  The U.S. Hawaii longline fishery ranged from 10$^{\circ}$ N to 35$^{\circ}$ N latitude and from 120$^{\circ}$ W to 175$^{\circ}$W longitude in 2024.   The total range exploited since 1991 extended from 5$^{\circ}$S to 50$^{\circ}$N latitude and from 125$^{\circ}$W to 175$^{\circ}$E longitude.   Effort by the U.S. Hawaii longline fishery was a record 65.9 million hooks set in 2024.  The record effort was due to more hooks set by the deep-set sector of the longline fishery which accounted for 99% of the total number of hooks set and an expansion of longline fishing outside of the U.S. EEZ in 2024.

Longline catch of blue marlin increased rapidly from 37 mt 1987 to 378 mt in 1990 and remained stable through 1997.  Blue marlin catches then declined to 197 mt in 1997 and was on an increasing trend peaking at 687 mt in 2019.  Plots of the geographic distribution of blue marlin catches (number of fish) show that the highest catches occurred south-southwest of the main Hawaiian Islands (15$^{\circ}$N-20oN and 155$^{\circ}$W-165$^{\circ}$W) (Figs. 3 & 4).  Catches of blue marlin exhibit strong seasonal cycles.  Blue marlin catches were usually highest in the second and third quarters of the year.

Size frequency of blue marlin.

The American Samoa based longline fishery prior to the 1990s was primariliy a troll fishery, Horizontal longlining was first introduced to American Samoa in 1995. Participation in this fishery peaked in 2003 with 38 vessels, but more recently around 10 vessels have been actively fishing, with the number of hooks set, number of sets, and number of vessels declining. The American Samoa longline fishery primarily targets South Pacific Albacore and yellowfin tuna for their cannery. Two other important characteristics of this fishery are its geographic range and the annual number of hooks set.  The U.S. American Samoa longline fishery primarily fishes within it EEZ.   Effort by the U.S. American Samoa longline fishery was 4.06 million hooks set in 2024. Longline catch of blue marlin 

### Hawaii, Guam, and CNMI Troll Fisheries

The troll fisheries in Hawaii, Guam, and CNMI are hook and line fisheries that use fishing gear consisting of fiberglass rods, reels and artificial lures typically made of resin or chrome metal heads dressed with colored rubber skirts (Rizzuto, 1977).  Live bait bridled to hooks are also used to catch marlins and other pelagic fishes.   This fishery targets tunas, marlins and other pelagic species such as mahimahi (*Coryphaena spp.*) and wahoo (*Acanthocybium solandri*).  Fishing is conducted from relatively small boats, e.g. <15 m.

The number of troll fishers ranged from 1,704 in 1988 to 2,367 in 1999 with 1,805 fishers in 2019.  Seventy-one percent of the troll fishers were from Hawaii, 26% from Guam and 3% from CNMI in 2019.  The duration of a typical troll trip is one day.  Since this fishery employs small vessels, most trips remain within 100 km from shore, well inside the 200 mile U.S. EEZ.

Blue marlin was the predominant component of troll marlin catch.  Blue marlin catch peaked at 434 mt in 1996, declined to a record low 128 mt in 2007, and was 178 mt in 2024 (Table 5).



### Hawaii Handline Fishery

The Hawaii handline fishery, which targets tunas, includes day and night components known as the “palu ahi” and “ika shibi” fisheries, respectively.  The daytime handline fishery employs “palu” (chum in Hawaiian) to evoke a feeding frenzy in an aggregation of juvenile “ahi” (tuna in Hawaiian) and hook the catch with a handline.  The nighttime handline fishery has two sets of gear, one used to catch the “ika” (squid in Japanese) for bait and the other for catching large “shibi” (tuna in Japanese) (Yuen 1979).  

There were 444 handline fishers in 2019.  The duration of a handline trip is typically one day for the daytime handline fishery and one night for the nighttime handline fishery.  As with the troll fisheries, most handline trips remain within 100 km from shore, although some handline fishers operate offshore by seamounts and weather buoys on multiple day trips.

Marlins are rarely caught by the handline fishery and represent only a small proportion of its overall catch.  This fishery caught relatively small amounts of striped and blue marlins when compared to the longline and troll fisheries.  There has been no striped marlin catch by the handline fishery from 2005.  The highest striped marlin catch was 2 mt in 2001 (Table 6).  Handline catch of blue marlin were higher in the earlier years, peaked at 9 mt in 1997 and was 5 mt in 2019.

## DATA SOURCES

### Category I: Annual Catch Data

Category I catch statistics refer only to the quantity of fish kept and landed.  Catch that was discarded or released was not included.  Several sources of fisheries dependent data for the longline, troll, and handline fisheries are collected by Federal (NOAA Fisheries Service), State (Hawaii), and Pacific Island (Guam and CNMI) agencies and used in combination by staff of the NOAA Pacific Islands Fisheries Science Center (PIFSC).  The duration and coverage (i.e., percent of catch reported) varied amongst the different data sources (Table 7).
 
Estimated catches are reported in this paper as whole weights.  Some fish were landed whole while others were processed at sea, e.g., headed and gutted or gilled and gutted.  The recorded weight of individual processed fish was adjusted by applying a conversion factor depending on the degree of processing (Table 8).  This step increased the nominal weight of processed catch to a whole weight estimate to account for the weight loss.  Likewise, to account for missing market sample days, sample data were extrapolated to represent full coverage to estimate total landings.  

Data sets were combined to estimate annual catch statistics for certain fisheries.  For example, the U.S. longline fishery catch was estimated from Federal logbook data, market sample data, and State of Hawaii, Division of Aquatic Resources (Hawaii DAR) Commercial Marine Dealer data.  The numbers of fish kept, as recorded in longline logbooks, are multiplied by the mean weights of landed fish, estimated from the PIFSC market sample data or the Hawaii DAR Commercial Marine Dealer data.

### Marlin Species Identification Issues

Since blue marlin, striped marlin, and black marlin are similar in appearance, a longstanding problem in monitoring the Hawaii-based longline fishery at the NOAA PIFSC has been the accuracy of species identifications for the istiophorid billfishes.  This problem has primarily affected logbook data, but some fishery observers, particularly newly-hired individuals, have also erred in species identifications.  A long-term project to correct these problems was completed for the years 1995 through 2003.  Its principal output consisted of one paper emphasizing blue marlin that was published in a peer-reviewed scientific journal that addressed the five istiophorid species (Walsh *et al.,* 2005).  A subsequent document showed the overall marlin counts in the Hawaii-based longline logbook data were reasonably accurate but blue marlin was overlogged by 18% while striped marlin was underlogged 11% during the study period (Walsh, *et al.,* 2007, Figure 9).  The document can be obtained from the PIFSC’s website at:
  
http://www.pifsc.noaa.gov/library/pubs/tech/NOAA_Tech_Memo_PIFSC_13.pdf


### Category II: Spatial Catch and Effort Data

Year, area fished, catches and effort are the most important information included in Category II data reporting.  The U.S. longline fishery provided Category II data calculated from Federal logbook and Hawaii DAR Commercial Marine Dealer data.  The combination of data sets was sufficient to generate area-specific summaries of catch and effort.  
  
### Category III: Biological (size composition) Data

Biological measurements were obtained for the Hawaii longline, troll, and handline fisheries. Raising factors were applied to the market sample and Hawaii DAR Commercial Marine Dealer data if the fish was processed to yield an estimated whole weight (Table 7). Weight-frequency distributions for striped marlin and blue marlin were produced from HDAR Commercial Marine Dealer data. 

The Pacific Islands Fishery Observer Program (PIROP) provides detailed set-by-set data on the Hawaii-based longline fishery including the eye-fork length of fish caught in cm and a variety of operational variables, among them: location as latitude and longitude, vessel ID, hooks per float, and total number of hooks set, among others. Data are collected following the procedures outline in the PIROP observer manual (Pacific Islands Regional Office, 2017). Data were extracted from the PIROP database on 15 October 2020. 

Blue marlin are caught as non-target species in both the deep-set tuna-targeting and shallow-set swordfish-targeting sectors of the Hawaii-based longline fleet. Observers were first placed onboard longline vessels in 1994. Observer coverage varied significantly prior to 2000, with observer coverage between 3.3 and 10.4% each year for the entire fishery (NMFS, 2017). Due to interactions with protected species the shallow-set sector was closed from 2001 to2004 and when it was reopened, 100% observer coverage occurred on shallow-set trips and ~20% observer coverage occurred on deep-set trips (Gilman *et al.,* 2007). The deep-set trips are typically further south than the shallow-set trips, which are concentrated around the sub-tropical frontal zone (STFZ) where large swordfish are caught (Bigelow *et al.,* 1999). Here, deep-sets are defined as sets with greater than 10 hooks per float prior to 2004 and greater than 14 hooks per float after 2004. This has been shown to better identify the recorded targeted fish by fishers than using greater than 14 hooks per float for all years (Sculley, 2019). 

Prior to 2006 observers measured every fish caught. Since 2006, observers measured every third fish caught, regardless of species. Spatial plots are in 5x5 degree squares where cells with fewer than three vessels measuring blue marlin are excluded for confidentiality. Figures were made in R (version 3.4.0, R Core Team, 2017).

The mean eye-fork length of blue marlin caught in the Hawaii-based longline fishery was 165 cm. The size of blue marlin caught each year varied slightly between 160 and 180 cm EFL for most of the years in the time series (Figure 10). A single peak in length for blue marlin at around 165 cm EFL (Figure 11), and there does not appear to be substantial differences in mean length by quarter (Figure 12). There does not appear to be significant differences in the length of blue marlin caught in the deep- and shallow-set sectors of the longline fleet (Figure 13) nor between male and female blue marlin, although the size differences do not tend to be as large at the smaller sizes caught by the Hawaiian longline fleet (Figure 14).

The spatial patterns of fish size by length are illustrated in Figure 15 and Figure 16. The largest fish are caught north and east of the Hawaiian Islands while those caught to the south and west are smaller. Overall, fish tend to be larger in quarters two and three. Overall, it appears that the Hawaii-based longline fishery catches primarily small blue marlin as non-target species. Mean eye-fork length has been relatively consistent throughout the time series. Larger fish are typically caught to the north of Hawaii and smaller fish are typically caught to the south of Hawaii.  
	
3. REFERENCES

Bigelow, K. A., C. H. Boggs and He, X. I. 1999. Environmental effects on swordfish and blue shark catch rates in the US North Pacific longline fishery. Fisheries Oceanography 8(3): 178-198.

Brodziak, J. and Dreyfus, M. 2011. Annex 11: Report on the Seminar on the Use of the Best Available Scientific Information. 22 July 2011. ISC.

Gilman, E., D. Kobayashi, T. Swenarton, N. Brothers, P. Dalzell and Kinan-Kelly, I. 2007. Reducing sea turtle interactions in the Hawaii-based longline swordfish fishery. Biological Conservation 139(1–2): 19-28.

International Scientific Committee.	2010.  Report of the Billfish Working Group Workshop.  Honolulu, Hawaii. 30 November–4 December 2010.

International Scientific Committee. 2011.  Report of the Billfish Working Group Workshop.  Honolulu, Hawaii. 19-17 January 2011.
 
Ito R.Y., Dollar R.E., Kawamoto K.E. 1994.  The Hawaiian longline fishery for swordfish.  International Symposium on Pacific Swordfish: Development of Fisheries, Markets, and Biological Research. Ensenada, Baja California, Mexico, December 11-14, 1994.

Ito, R.Y. and W.A. Machado. 	2001.  Annual report of the Hawaii-based longline fishery for 2000.  Southwest Fisheries Science Center Administrative Report H-01-07, 55 p.  		
Kawamoto K.E., Ito R.Y., Clarke R.P., Chun A.A. 1989.  Status of tuna longline fishery in Hawaii, 1997-88.  Southwest Fisheries Science Center Administrative Report H-89-10, 33 p. 

NMFS. 2017. Hawaii longline fishery logbook statistics -non-confidential summary tables. Available online at http://www.pifsc.noaa.gov/fmb/reports.php, accessed 8 May 2017. National Marine Fisheries Service, Pacific Islands Fisheries Science Center, Honolulu.

Pacific Islands Regional Office. 2014.  Hawaii Longline Regulation Summary.  10p. 

Pacific Islands Region Office (PIRO). 2017. Hawaii Longline Observer Program Observer Field Manual. Version LM.17.02. National Oceanic and Atmospheric Administration, Pacific Islands Region, Honolulu, Hawai‛i.

R Core Team 2017. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.

Rizzuto, J. 1977.  Modern Hawaiian Gamefishing.  University Press of Hawaii.  254 p. 

Sculley, M. 2019. Standardization of the Striped Marlin (Kajikia audax) Catch per Unit Effort Data Caught by the Hawaii-based Longline Fishery from 1994-2017 Using Generalized Linear Models. ISC/2019/BILLWG-01/06.

Walsh W. A., R.Y. Ito, K.E. Kawamoto, and M. McCracken. 2005.  Analysis of logbook accuracy for blue marlin (Makaira nigricans) in the Hawaii-based longline fishery with a generalized additive model and commercial sales data. Fisheries Research 75:175–192

Walsh, W. A., K. A. Bigelow and R. Y. Ito 2007.  Corrected Catch Histories and Logbook Accuracy for Billfishes (Istiophoridae) in the Hawaii-based Longline Fishery. NOAA Technical Memorandum NMFS-PIFSC-13, 33 p.

Yuen, H.S.H. 1979.  A night handline fishery for tunas in Hawaii.  Marine Fisheries Review 41(8): 7-14.

## Tables

```{r}
#| label: tbl-annualcatch
#| echo: false
#| tbl-cap: Annual U.S. Commercial fisheries blue marlin catch in the Pacific Ocean, by fleet. Hawaii and American Samoa longline catch is in numbers, US Other catch is in metric tons.

AnnualCatchTable<-AnnualCatch %>%
            pivot_wider(
                names_from = Source,
                values_from = C_BLUE_MARLIN
            )
AnnualCatchTable<-subset(AnnualCatchTable, YEAR>=1993)

AnnualCatchTable %>%
    gt(rowname_col= "YEAR") %>%
    fmt_number(
        columns = c(2,3),
        decimals = 2
    )   %>% 
     fmt_number(
        columns = c(4),
        decimals = 0
    ) %>%
    sub_missing(
        missing_text= "-"
    ) %>% 
    fmt_integer(columns = YEAR, use_seps =FALSE) %>%
    tab_stubhead(label = "Year")




```

